# Generated by Django 4.0.3 on 2022-04-23 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_messages_sender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='filter',
        ),
        migrations.DeleteModel(
            name='formregistration',
        ),
        migrations.DeleteModel(
            name='messages',
        ),
        migrations.DeleteModel(
            name='reviews',
        ),
        migrations.DeleteModel(
            name='userimage',
        ),
    ]
