# Generated by Django 4.0.3 on 2022-04-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_formregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='formregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('job', models.CharField(max_length=20)),
                ('jobtype', models.CharField(max_length=20)),
                ('field', models.IntegerField()),
                ('wage', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=60)),
                ('about', models.CharField(max_length=100000000000000000)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
